#!/sbin/busybox sh

ZRAM_DEVICES="zram0 zram1 zram2 zram3"
ZRAM_SIZE="629145600"
NUM_DEVICES="4"

# reset (no need to loop)
swapoff /dev/block/zram0 > /dev/null 2>&1 &
swapoff /dev/block/zram1 > /dev/null 2>&1 &
swapoff /dev/block/zram2 > /dev/null 2>&1 &
swapoff /dev/block/zram3 > /dev/null 2>&1
echo 1 > /sys/block/zram0/reset &
echo 1 > /sys/block/zram1/reset &
echo 1 > /sys/block/zram2/reset &
echo 1 > /sys/block/zram3/reset

for ZRAM_DEVICE in $ZRAM_DEVICES; do
	if [[ -e "/sys/block/$ZRAM_DEVICE/disksize" && -e "/dev/block/$ZRAM_DEVICE" ]]; then
		echo `expr $ZRAM_SIZE \/ $NUM_DEVICES` > "/sys/block/$ZRAM_DEVICE/disksize"
		mkswap "/dev/block/$ZRAM_DEVICE"
		swapon "/dev/block/$ZRAM_DEVICE"
	fi
done

echo 80 > /proc/sys/vm/swappiness

exit 0
